name: Notificação no Discord

on:
  push:
    branches: [main]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar notificação para o Discord
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "content": "Novo push na main!\n**Autor:** '"${{ github.actor }}"'\n**Mensagem:** '"${{ github.event.head_commit.message }}"'\n**Repositório:** '"${{ github.repository }}"'\n**Link:** '"${{ github.event.head_commit.url }}"'"
          }' \
          ${{ secrets.DISCORD_WEBHOOK }}
